# Generated by Django 3.1.5 on 2021-03-31 06:09

import default_image.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20210328_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=default_image.fields.DefaultStaticImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
