# Generated by Django 3.1.5 on 2021-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_auto_20210331_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='testexkt', max_length=20, unique=True),
        ),
    ]
