# Generated by Django 3.1.5 on 2021-02-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0004_scrap_date'),
        ('listapp', '0002_auto_20210204_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraplist',
            name='scrap',
            field=models.ManyToManyField(to='scrapapp.Scrap'),
        ),
    ]
