# Generated by Django 3.1.5 on 2021-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_scraplist_scrap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scraplist',
        ),
    ]
