# Generated by Django 3.1.5 on 2021-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=128, verbose_name='맥주 이름')),
                ('place', models.CharField(max_length=128, verbose_name='장소')),
                ('flavor', models.CharField(max_length=128, verbose_name='맛')),
                ('context', models.TextField(verbose_name='내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
        ),
    ]
