# Generated by Django 3.1.5 on 2021-02-22 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapapp', '0005_scrap_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
