# Generated by Django 3.1.5 on 2021-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='picture',
            field=models.ImageField(null=True, upload_to='scrap/', verbose_name='사진'),
        ),
    ]
