# Generated by Django 3.1.5 on 2021-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0003_auto_20210210_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='date',
            field=models.DateField(null=True, verbose_name='마신 날짜'),
        ),
    ]
