# Generated by Django 3.1.5 on 2021-03-04 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0006_auto_20210222_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점'),
        ),
    ]
