# Generated by Django 3.1.5 on 2021-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0006_auto_20210222_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='lat',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='lng',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
    ]
