# Generated by Django 3.1.5 on 2021-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0007_auto_20210305_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='lat',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='lng',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
