# Generated by Django 3.1.5 on 2021-03-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0008_auto_20210305_2132'),
        ('scrapapp', '0007_scrap_rating'),
    ]

    operations = [
    ]
