# Generated by Django 3.1.5 on 2021-03-08 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0009_merge_20210308_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점'),
        ),
    ]
