# Generated by Django 3.1.5 on 2021-03-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0010_auto_20210310_0214'),
        ('scrapapp', '0010_auto_20210308_2246'),
    ]

    operations = [
    ]
