# Generated by Django 3.1.5 on 2021-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0011_auto_20210310_2114'),
        ('scrapapp', '0011_merge_20210312_0248'),
    ]

    operations = [
    ]
