# Generated by Django 3.1.5 on 2021-03-16 12:10

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0014_auto_20210316_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to='scrap/', verbose_name='사진'),
        ),
    ]
