# Generated by Django 3.1.5 on 2021-05-13 08:32

import default_image.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='bitter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='beer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='fruity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='genre',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='beer',
            name='hoppy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='image',
            field=default_image.fields.DefaultStaticImageField(blank=True, null=True, upload_to='beer/'),
        ),
        migrations.AddField(
            model_name='beer',
            name='malty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='num_scraps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='place1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='beer',
            name='place2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='beer',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='sour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='sweet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
