# Generated by Django 3.1.5 on 2021-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0002_auto_20210513_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='bitter',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='fruity',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='hoppy',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='malty',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='num_scraps',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='place1',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='place2',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='sour',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='sweet',
        ),
    ]
